---
trigger:
  branches:
    exclude:
      - main
  paths:
   include:
    - environments/staging
    - modules

pool: 'DJB PreProd Pool'

jobs:
  - template: templates/terragrunt_plan.yml
    parameters:
      environment: staging
      module: base
      subscription: "DJB PreProd (via service principal)"
      backend_storage_resource_group: "rg-djb-devops-dev"
      backend_storage_account_name: "sadjbstagingtfstate"
      application_name: "base"

  - template: templates/terragrunt_plan.yml
    parameters:
      environment: staging
      module: applications
      subscription: "DJB PreProd (via service principal)"
      backend_storage_resource_group: "rg-djb-devops-dev"
      backend_storage_account_name: "sadjbstagingtfstate"
      application_name: "applications"
