---
trigger:
  branches:
    exclude:
      - main
  paths:
   include:
    - environments/staging/*
   exclude:
    - environments/production/*

pool: 'sc-djb-preprod'

variables:
  - group: hsk-infra-staging

jobs:
  - template: templates/terragrunt_plan.yml
    parameters:
      environment: staging
      module: base
      subscription: "DigitalJuryBundle (Non-Production)"
      backend_storage_resource_group: "rg-djb-dev"
      backend_storage_account_name: "sadjbdevtfstate"
      application_name: "base"
      tfmodules_network: "network"

  - template: templates/terragrunt_plan.yml
    parameters:
      environment: staging
      module: applications
      subscription: "DigitalJuryBundle (Non-Production)"
      backend_storage_resource_group: "rg-djb-dev"
      backend_storage_account_name: "sadjbdevtfstate"
      application_name: "applications"
      tfmodules_network: "network"
